#Splash screen properties
#Wed May 13 06:47:00 KST 2026
barBorder=0x5D4037
resourcePackPath=resources
enabled=true
background=0xF2E8C9
bar=0x5D4037
logo=0x5D4037
barBackground=0xD7CCC8
logoTexture=seongoo_loadingbar\:textures/gui/title/mojang.png
